### ISSUE TITLE
Support iterators?

### ISSUE THREAD

**Issue by kvark** [CasualX/bitset-core#1]
It would be nice to be able to iterate all positions of `1`, or all positions of `0`. The assumption is that the implementation can be more efficient than just a `for` loop that checks each bit.

**Comment by CasualX** [comment]
Unfortunately this is tricky. Anything other than 'loop over all bits' requires custom iterator types depending on the concrete type.

Doing such custom iterators may require generic associated lifetimes (currently not supported in Rust). It may also require having the BitSet trait know about its underlying container (whether it's stored as `u8` or `u32` etc) which is what I'm trying to avoid.

Perhaps this can be solved with a separate trait (akin to `IntoIterator` but for bit sets) but that would also introduce a lot more API surface than I was comfortable with when I initially made this crate.

In the end I didn't personally need high performant iteration of set or cleared bits so I left it out.

**Comment by kvark** [comment]
Feel free to close the issue then. For now, I'm using `bit-set` in https://github.com/gfx-rs/gfx-extras/pull/35
